# Generated by Django 5.0.6 on 2025-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'blank': 'نام کاربری نمی\u200cتواند خالی باشد.', 'unique': 'این نام کاربری قبلاً استفاده شده است.'}, max_length=150, unique=True, verbose_name='نام کاربری'),
        ),
    ]
