# Generated by Django 5.2 on 2025-09-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_cancel_by_alter_order_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
